# Generated by Django 3.2.7 on 2021-09-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pressure',
            field=models.CharField(max_length=4),
        ),
    ]
