# Generated by Django 3.2.7 on 2021-09-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='number_of_measure',
            field=models.IntegerField(default=0),
        ),
    ]
