# Generated by Django 3.2.7 on 2021-09-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0003_auto_20210918_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
