# Generated by Django 3.2.7 on 2021-09-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph_app', '0004_alter_time_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressure',
            name='pressure',
            field=models.FloatField(),
        ),
    ]
